export const enum QUERYE_KEYS {
	LOGIN = 'login',
	REGISTER = 'register',
	GET_PROFILE = 'get-profile',
	UPDATE_PROFILE = 'update-profile',
	CHANGE_PASSWORD = 'change-password',
	UPLOAD_AVATAR = 'upload-avatar',
	GET_PACKS = 'get-icon-pack',
	GET_ICONS = 'get-icons',
	PATCH_ICON_FOR_USER = 'patch-icon',
	ACTIVATE_TWO_FA = 'activate-two-factor',
	DEACTIVATE_TWO_FA = 'deactivate-two-factor',
	SEND_CODE = 'send-code',
	GET_COMMUNITY = 'get-community',
	GET_COMMUNITY_BY_ID = 'get-community-by-id',
}
